CREATE TABLE IF NOT EXISTS items (
    id SERIAL PRIMARY KEY,
    product_id INTEGER NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    is_active BOOLEAN DEFAULT true,
    activate_if_possible BOOLEAN DEFAULT true,
    name VARCHAR(255),
    ref_id VARCHAR(255),
    packaged_height DECIMAL(10, 4),
    packaged_length DECIMAL(10, 4),
    packaged_width DECIMAL(10, 4),
    packaged_weight_kg DECIMAL(10, 4),
    height DECIMAL(10, 4),
    length DECIMAL(10, 4),
    width DECIMAL(10, 4),
    weight_kg DECIMAL(10, 4),
    cubic_weight DECIMAL(10, 4),
    is_kit BOOLEAN DEFAULT false,
    reward_value DECIMAL(10, 4),
    estimated_date_arrival TIMESTAMP,
    manufacturer_code VARCHAR(255),
    commercial_condition_id INTEGER,
    measurement_unit VARCHAR(50) DEFAULT 'un',
    unit_multiplier DECIMAL(10, 4) DEFAULT 1.0000,
    modal_type VARCHAR(100),
    kit_itens_sell_apart BOOLEAN DEFAULT false,
    sku VARCHAR(32) UNIQUE,
    price DECIMAL(10, 2) NOT NULL,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);